### ISSUE TITLE
Manual invalidation

### ISSUE THREAD

**Issue by nicholaswyoung** [tgriesser/checkit#36]
Is it possible to do something like:

```javascript
// schema is a `checkit` object.
schema.invalidate('path', 'error message');
```

I'm working on a new project where manual invalidation could be very helpful. In my head this (potential) API would work regardless if the schema has already been ```run()``` or not.

**Comment by rhys-vdw** [comment]
Right. So just to actually generate the error message manually? Sounds like a useful addition. I'll take a PR.

**Comment by NinjaBanjo** [comment]
@nicholaswyoung can you provide a use case for this? Right now all of Checkit's validation is done in a single call and your provided a return by way of `err, res` or a promise if async.

Being able to invalidate something manually would require interrupting the validation process or somehow providing a reference to the current validation cycle in a custom rule function.

**Comment by nicholaswyoung** [comment]
@ninjabanjo My apologies... I thought this issue was closed long ago. I'm not using CheckIt anymore, so my request is irrelevant.
