### ISSUE TITLE
target in custom validators

### ISSUE THREAD

**Issue by Scottjutsu** [tgriesser/checkit#42]
Might be worth documenting that in adding custom validators to the Checkit.Validator object's prototype you have to use this._target to access the target object (as opposed to this.target as used in the custom rule example).  

Happy to do a PR if desired.

**Comment by rhys-vdw** [comment]
Hi @Scottjutsu. That could be useful, but is there any advantage to extending the prototype over providing custom rules as described? I'm hesitant to document private variables.

**Comment by Scottjutsu** [comment]
Fair point.  I suppose the primary advantage is that you can share custom rules without having to inherit them from a common parent model.  You also get consistency in always using strings to set your rules - could be useful in automated testing.

**Comment by rhys-vdw** [comment]
> the primary advantage is that you can share custom rules without having to inherit them from a common parent model

What's a 'model' in this context?

**Comment by Scottjutsu** [comment]
A bookshelf.js model.

**Comment by rhys-vdw** [comment]
Sure, I'll accept a PR. Sounds like info that should be in the relevant section the readme. Is the use of `this.target` incorrect in the docs?

**Comment by rhys-vdw** [comment]
Closed by #44.
