### ISSUE TITLE
string validator?

### ISSUE THREAD

**Issue by LordWingZero** [tgriesser/checkit#50]
I see the alpha stuff but nothing seems to also take into account numbers and special chars.

Do I need to use my own?

````Javascript
function string(val) {
    if (typeof(val) !== "string") {
        throw new Error('Value must be a string.');
    }
}

````

**Comment by rhys-vdw** [comment]
@LordWingZero you'll have to read the source. If you find an answer it would be good if you could open a PR either adding the feature and/or updating the docs.
