### ISSUE TITLE
Transform the property after validate

### ISSUE THREAD

**Issue by Chubby-Chocobo** [tgriesser/checkit#80]
Hi, I'm using Checkit in my web project to validation the request's parameters like this:
```
var [err, params] = new Checkit({
      id: ['required', 'naturalNonZero']
    }).validateSync(req.params);
```
But the type of `params.id` is still string. I want it to be integer actually.
or another case:
```
var [err, params] = new Checkit({
      tags: ['parseableNumericArray'],
    }).validateSync(req.params);
```
with `parseableNumericArray` is a customized validation. I think if `params.tags` can be array of number instead of string after validation, it would be great.

Can we do that with Checkit currently? Or can I make a pull request? Is this project being maintained? I see it's a while since the last update...
Thanks for your attention.

**Comment by joepie91** [comment]
I would argue that it's only `checkit`s job to *validate* your values, not to modify or use them in any way. In the interest of keeping the module focused, it's probably better if you convert the value yourself after the validation has passed.

**Comment by Chubby-Chocobo** [comment]
It's ok then.
