### ISSUE TITLE
Front page text truncated

### ISSUE THREAD

**Issue by machineghost** [tgriesser/checkit#96]
The front page/readme file has the following:

> It supports both sync

It looks like something got chopped off there on accident, and maybe the full sentence should be something like:

> It supports both synchronous and asynchronous operation.

**Comment by rhys-vdw** [comment]
You can open a PR if you like.

**Comment by machineghost** [comment]
As it turned out your library wasn't what I was looking for, but you can leave invalid English on the front page of your project if you like.
